### PR TITLE
nasl-syntax: add fuzz target to fuzz parser.

### PR DESCRIPTION
**Pull request by sepehrdaddev**
**What**:
Adds fuzz target to fuzz nasl_syntax::parse.

**Why**:
To find bugs with in the implementation.

### CODE REVIEW

**Comment by sepehrdaddev** [comment]
to run the fuzzer, you can run the following command:

```sh
cd rust/nasl-syntax && cargo +nightly fuzz run fuzz_parse
```

you need to make sure that you have [cargo-fuzz](https://rust-fuzz.github.io/book/cargo-fuzz/setup.html) setup correctly (it also requires a C compiler such as gcc).

**Comment by sepehrdaddev** [comment]
the dependency-review fails because of license of [jobserver](https://crates.io/crates/jobserver) (`MIT/Apache-2.0`) I think, [this](https://github.com/greenbone/actions/blob/main/dependency-review/action.yml#L42) needs to be adjusted.

**Comment by ArnoStiefvater** [comment]
Hey @sepehrdaddev,

Thanks a lot for your contribution.

We are currently in the works of adjusting contributor processes for our new Rust based code. This means this PR will probably not be merged this or next week.

**Comment by sepehrdaddev** [comment]
@ArnoStiefvater no problem!

no worries, there is no rush in getting it merged.

**Comment by ArnoStiefvater** [comment]
Hey @sepehrdaddev,

We have now adjusted the contributor processes a bit.

Please see https://github.com/greenbone/openvas-scanner/tree/main/RELICENSE for more information.

TDLR: Include a commit with the contribution agreement in this PR.

Feel free to ask questions If you have any.

**Comment by sepehrdaddev** [comment]
Hey @ArnoStiefvater,

I have added the contribution agreement, pls let me know if its good or not.

also, if you guys are interested, I can setup the GH Actions workflow for [clusterfuzzlite](https://google.github.io/clusterfuzzlite/) so the fuzzer can run on PRs and etc.

**Comment by ArnoStiefvater** [comment]
Thanks, looks good.

We will probably merge this PR early next week.

[clusterfuzzlite](https://google.github.io/clusterfuzzlite/) looks interesting but we have some policies in regards to using GitHub Actions form outside our organization. Another point is that fuzzers take a long time to run and use up some resources so maybe not optimal for PRs. Thanks for your offer but I don't see it included in the near future.

**Comment by jjnicola** [comment]
MIT/Apache2.0 is non-spdx compliant. I have created the PR rust-lang/jobserver-rs#63 for fixing the license issue.

**Comment by jjnicola** [comment]
Hi @sepehrdaddev, 
it seems that the license issue which was blocking this PR was already solved. jobserver dependency should have a SPDX compliant license name. Could you please update/re-push the PR ? Then, It can merge.
Thanks in advance.

**Review by jjnicola — APPROVED** [review]

**Review by ArnoStiefvater — APPROVED** [review]

**Pull request merged**
