### PR TITLE
Remove ability to send NVT info over OTP.

### PR DESCRIPTION
**Pull request by kroosec**

### CODE REVIEW

**Comment by clems4ever** [comment]
Hello @kroosec ,
I was reviewing the PRs and came accross this one. I wonder why you're removing that command? It seems to me like a breaking change.
Where would you gather the plugin info from after that change? The manager?

Thanks.

**Comment by jjnicola** [comment]
Hello @clems4ever,
This PR is related to future changes.
You can find an explanation about it here https://community.greenbone.net/t/goodbye-otp/1739.
Regards,
Juan

**Comment by clems4ever** [comment]
Ok, clearer now.

**Comment by janowagner** [comment]
This PR is replaced by the new PR https://github.com/greenbone/openvas-scanner/pull/333

**Pull request closed without merging**
